### ISSUE TITLE
Memoize or cache DirectionStrategy

### ISSUE THREAD

**Issue by DaddyWarbucks** [bondz/react-static-google-map#42]
Thanks for the work on this tool! It is really great and I have enjoyed using it, especially alongside   [react-google-maps](https://github.com/tomchentw/react-google-maps), where the component API's are very similar.

I have noticed that whenever a component above a `Direction` causes a re-render that the `Direction` component flashes as it is using the `Async` component under the hood. I have also sussed out that there really is no way to use something like `PureCompnent` because the components themselves return `null` and are really just declarative ways of building a strategy which `StaticGoogleMap` renders as an image (which is really cool, btw).

But there has to be some way to memoize (or otherwise cache) the fetch call to the directions API. Have you thought about or experimented with this at all? I would like to open a PR but wanted to get someone's thoughts on it first.

After a quick look, I think that we could do something in this area: https://github.com/bondz/react-static-google-map/blob/41ba1f958b5914273180b5825568c7c9856c192b/src/strategies/direction/index.js#L46
Perhaps store the `JSON.stringify(data)` as the key in a Map/object with the result of the promise. And then later check to see if that key exists and if so return the stored path (not as a promise). Then I believe that as per https://github.com/bondz/react-static-google-map/blob/41ba1f958b5914273180b5825568c7c9856c192b/src/components/StaticGoogleMap.js#L133
the `StaticGoogleMap` will just consume that and return the component instead of the async component.

Any thoughts?

**Comment by DaddyWarbucks** [comment]
@bondz Any thoughts on this? Would you be open to reviewing a PR? I am using this library on two projects currently and would like to use it on a third as well. Rather than forking it and maintaining my own version, I would prefer to help improve this one.

**Comment by bondz** [comment]
@DaddyWarbucks I completely missed this the first time around, apologies. Of course, I'm open to a PR. Happy to hear that the project has been useful for you.

I haven't though about an optimisation strategy for the directions component, but your idea should work. I'll look into it.

**Comment by DaddyWarbucks** [comment]
Sounds great; thanks for the response! I may have some free time later this week to whip up a PR.
