### ISSUE TITLE
Markers not appended in Next.js apps

### ISSUE THREAD

**Issue by lkbr** [bondz/react-static-google-map#5]
Hi there,
Thank you for this package. It's a breathe of fresh air in the forest of static google map renditions 👍 

I came across what I think is an issue when trying this in a [Next.js](https://github.com/zeit/next.js) app. I'm guessing this has to do with SSR: 
- minimal example repo: https://github.com/lkbr/next-map
- live version: https://next-map-mtxxmlqsse.now.sh (might take a bit to wake up)

---
running `yarn dev` produces:
![screen shot 2018-01-23 at 09 37 51](https://user-images.githubusercontent.com/544238/35268536-4d5f8234-0021-11e8-9e9a-e2f913571549.png)

running `yarn build` and `yarn start` (what see in the live version):
![screen shot 2018-01-23 at 09 38 56](https://user-images.githubusercontent.com/544238/35268552-55d0e12e-0021-11e8-8952-8f8da908d04b.png)

Looking at the generated image url of the live version you can see that the marker coordinates are not being appended to the url: `https://maps.googleapis.com/maps/api/staticmap?size=100x100&scale=1&format=png&maptype=roadmap&key=xxx&`

When first running `yarn dev` and refreshing the browser I get this in the terminal console:
```
Warning: setState(...): Can only update a mounting component. This usually means you called setState() outside componentWillMount() on the server. This is a no-op.

Please check the code for the Async component.
```

I wonder if that has something to do with it. Appreciate any help.

**Comment by bondz** [comment]
Would look into this and get back to you. Thanks for providing a repro.

**Comment by bondz** [comment]
Try using version v0.4.2.

**Comment by lkbr** [comment]
I appreciate you looking into this. SSR is working! However, now client side doesn't work on Next.js Apps. See: https://next-map-doceyulxpe.now.sh. Updated code is here: https://github.com/lkbr/next-map/commit/824bc5bc0aa2021f34acc798fc7ef6b14e7024ac

On load, the map is fine, but navigating (this happens client side see: https://github.com/zeit/next.js#with-link) between pages loads a blank map. Refreshing (which forces SSR) loads a complete map.

If you feel this is starting to be more of a Next.js issue than something you'd like to support with your package, I completely understand.

**Comment by bondz** [comment]
You're right, found what the problem is. Turns our Next makes some changes to the children props which breaks some of the assumptions I made earlier. I'm looking into it and might have a fix for it soon. Thanks for the repro, it has helped immensely.

**Comment by bondz** [comment]
@lkbr try v0.5.0 Should fix the issue.

**Comment by lkbr** [comment]
I can confirm that this is fixed. Thank you very much!
