### ISSUE TITLE
403 error for signed Static maps API

### ISSUE THREAD

**Issue by Gl0ntz** [bondz/react-static-google-map#54]
`<StaticGoogleMap size="1000x600" className="img-fluid" apiKey="YOUR APIKEY" signature="Your secret">
      <Marker location="6.4488387,3.5496361" color="blue" label="P" />
</StaticGoogleMap>`

I was using the example code to render a static google maps image with a signature. But it keeps throwing a 403 error. Is there something I am doing wrong?

**Comment by DaddyWarbucks** [comment]
@Gl0ntz Are you able to display a standard `<img src="..path with key and signature" />` without this component? It is likely this is some config within your google account if so. Be sure to read this page about keys/clients/signatures
https://developers.google.com/maps/documentation/maps-static/dev-guide

**Comment by Gl0ntz** [comment]
I did go through the documentation. But the problem I have is that the URL parameters are dynamically generated and generating the signature requires you to enter the url parameters before hand. It would have been best to just be able to enter the secret into the field and let the library take care of the generation of the signature. But I understand that this approach would be a huge security issue because the front end will have access to the signing secret. 
Can you suggest a way for me to dynamically generate the URL with the secret ?

**Comment by DaddyWarbucks** [comment]
This is a tricky one...and also something I am going to need to implement soon as well. I have been hitting some usage quotas that will require me to do this. Unfortunately there is no easy way to do this with any SPA I don't think. With server rendered pages you have access to the URL before it leaves your server, but in a standard React app you will not. I can think of one hacky solution for now.

```js
class MyImage extends React.Component {
  state = { signature: undefined };
  handleOnGenerate = path => {
    const { signature } = this.state;
    if (!signature) {
      fetchToMyServerThatReturnsSignature(path).then(signature => {
        this.setState({ signature });
      });
    }
  };
  render() {
    const { signature } = this.state;
    <StaticGoogleMap
      // Render as a div bc src won't do anything on div?
      // Then after generated and signed switch to img which
      // will make the actual call to google static maps.
      as={signature ? 'img' : 'div'}
      onGenerate={this.handleOnGenerate}
      size="600x600"
      apiKey="YOUR_API_KEY"
      signature={signature}
    >
      <Marker location="6.4488387,3.5496361" color="blue" label="P" />
    </StaticGoogleMap>;
  }
}
```

I have not tested this. I also think adding a `src` to div is not valid HTML...but that is the hack.

Another, and probably better solution, would be to change the `rootUrl` property to that of your own server. Then have your server sign the request, send it to Google, and then send the response back to your own client.

**Comment by DaddyWarbucks** [comment]
@Gl0ntz I am going to go ahead and close this because I don't think this library can/should solve this problem any better than it already is. It would be irresponsible for us to promote the usage of signing requests with the secret on the client side.
I plan to solve this for my own use case by changing the `rootURL` (which I just realized is undocumented, I will update that) to that of my own server. 
```
<StaticGoogleMap
    rootUrl="https://www.my-server.com"
    size="600x600"
    apiKey="MY_API_KEY"
/>
```

This will cause the component to create an
```
<img src="https://www.my-server-com?size=600x600&key=MY_API_KEY" />
```

My server will intercept that, sign it by attaching the `signature`, and then send the results back. Let me know if you have any further questions.
