### ISSUE TITLE
Bump and publish new NPM version

### ISSUE THREAD

**Issue by DaddyWarbucks** [bondz/react-static-google-map#63]
There has been two new features added:
- `cache`: https://github.com/bondz/react-static-google-map/pull/45
- `scale`: https://github.com/bondz/react-static-google-map/pull/53

There have also been some minor version updates on dependencies via renovatebot and dependabot.

There has also been various README updates
- Include `rootUrl` property docs
- remove the actual `<img>` tags and replace them with markup. Because Google no longer allows free Maps keys, we need to display the markup rather than a broken img.

@bondz We should publish a new NPM version. The current version on NPM is 0.5.2, the current version in package.json is 0.5.1. I believe this is a patch so 0.5.3.

**Comment by bondz** [comment]
Awesome @DaddyWarbucks I'll get on publishing a new version right away.

**Comment by bondz** [comment]
@DaddyWarbucks published 0.5.3.
