### ISSUE TITLE
Error while using latest version

### ISSUE THREAD

**Issue by kieryk123** [bondz/react-static-google-map#71]
I have this error when I use your package. It comes from react-promise package. 

> Cannot find module /node_modules/react-promise/dist/react-promise.cjs.js'. Please verify that the package.json has a valid "main" entry

` code: 'MODULE_NOT_FOUND',
  path: '/node_modules/react-promise/package.json',
  requestPath: 'react-promise'`

Please check this and try to fix it.

**Comment by DaddyWarbucks** [comment]
I am unable to reproduce this. I started a fresh project using `create-react-app` and installed the latest version `0.5.4` and everything worked as expected.

Perhaps you should try reinstalling your deleting and reinstalling your node modules.

**Comment by Dashue** [comment]
Another one here
