### ISSUE TITLE
Is there any way I can change the color or mode for map?

### ISSUE THREAD

**Issue by rishiankush** [bondz/react-static-google-map#72]
I want to show the night mode for static map. So I am not able to figure out any solution for this yet.

Here is my source code:
`<StaticGoogleMap scale={4} className="static-map" size="600x200" apiKey="XYZ">
                <Marker.Group size={'tiny'}>
                    <Marker location="18.5204,73.8567" />
                    <Marker location="8.4657,-13.2317" />
                    <Marker location="38.9072,-77.0369" />
                    <Marker location="6.3156,10.8074" />
                    <Marker location="4.4419,15.2663" />
                </Marker.Group>
            </StaticGoogleMap>`

Is there any property or styling that I can add here to achieve night mode for map?

**Comment by DaddyWarbucks** [comment]
You should be able to accomplish this with the `style` prop.
See this link: https://developers.google.com/maps/documentation/maps-static/styling

**Comment by DaddyWarbucks** [comment]
@rishiankush I am going to close this. Please leave another comment if this solution did not work for you.
